repos:
  - repo: local
    hooks:
      - id: shellcheck-all-sh
        name: shellcheck -x ./*.sh
        entry: bash -c 'shellcheck -x ./*.sh'
        language: system
        pass_filenames: false
      - id: format-all-sh
        name: shfmt
        entry: bash -c './format.sh'
        language: system
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
        name: gitleaks detect (scan secrets)
        args: ["detect", "--source=.", "--redact"]