#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput > /dev/null 2>&1 && [[ "$(tput colors 2> /dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold)
  DIM=$(tput dim)
  RESET=$(tput sgr0)
  BLUE=$(tput setaf 4)
  GREEN=$(tput setaf 2)
  YELLOW=$(tput setaf 3)
  RED=$(tput setaf 1)
else
  BOLD=""
  DIM=""
  RESET=""
  BLUE=""
  GREEN=""
  YELLOW=""
  RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput > /dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say() { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1" opener=""
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if command -v wslview > /dev/null 2>&1; then
    opener="wslview"
  elif command -v explorer.exe > /dev/null 2>&1; then
    opener="explorer.exe"
  elif command -v xdg-open > /dev/null 2>&1; then
    opener="xdg-open"
  elif command -v open > /dev/null 2>&1; then
    opener="open"
  else
    warn "couldn't open a browser — visit it manually: $url"
    return
  fi

  "$opener" "$url" < /dev/null > /dev/null 2>&1 &
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ $reply =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f $ENV_FILE ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n $current ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z $input && -n $current ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh > /dev/null 2>&1 && gh auth status > /dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" > /dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh > /dev/null 2>&1 && gh auth status > /dev/null 2>&1; then
    if gh variable set "$name" --body "$value" > /dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  ((${#WRITTEN_ENV[@]})) && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  ((${#WRITTEN_SECRET[@]})) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if ((${#SKIPPED[@]})); then
    printf '\n'
    warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT="/home/tmendy/dotfiles"
NIXOS_FLAKE="$REPO_ROOT/nixos#zephyrusG14"
CONFIGURATION="$REPO_ROOT/nixos/modules/hosts/zephyrusG14/configuration.nix"
HARDWARE="$REPO_ROOT/nixos/modules/hosts/zephyrusG14/hardware.nix"
UBUNTU_ISO="ubuntu-26.04-desktop-amd64.iso"
UBUNTU_SHA256="487f87faaf547ea30e0aba4d5b53346292571256b25333a978db1692bcee9dd2"
GPARTED_ISO="gparted-live-1.8.1-3-amd64.iso"
GPARTED_SHA256="3f66b2e10b8bb2c573ed6cdd3a9b54fd0a8e7690634ab6b15c3c8f517992d1a1"
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
NIXOS_PREPARED_MARKER="/var/tmp/dual-boot-nixos-prepared"

download_dir() {
  local directory=""
  if command -v xdg-user-dir > /dev/null 2>&1; then
    directory=$(xdg-user-dir DOWNLOAD 2> /dev/null || true)
  fi
  printf '%s' "${directory:-$HOME/Downloads}"
}

find_local_iso() {
  local iso="$1" directory
  for directory in "${VENTOY_DIR:-}" "$SCRIPT_DIR" "$(download_dir)" "$HOME/Downloads" "$HOME/Téléchargements"; do
    if [[ -n $directory && -f "$directory/$iso" ]]; then
      printf '%s' "$directory/$iso"
      return 0
    fi
  done
  return 1
}

detect_ventoy_dir() {
  command -v findmnt > /dev/null 2>&1 || return 1
  findmnt -rn -o TARGET,LABEL 2> /dev/null |
    awk '$2 == "Ventoy" { print $1; exit }'
}

copy_iso_to_ventoy() {
  local source="$1" destination="$2" iso="$3"
  [[ -f "$destination/$iso" ]] && return 0
  [[ -n $source && -f $source ]] || return 1

  say "Copie de $iso vers Ventoy. Le fichier est volumineux, patientez quelques minutes."
  cp -- "$source" "$destination/$iso"
}

os_id() {
  sed -n 's/^ID=//p' /etc/os-release 2> /dev/null | tr -d '"' | head -n1
}

unallocated_mib_after_p2() {
  local disk_size p2_start p2_size
  disk_size=$(< /sys/class/block/nvme0n1/size)
  p2_start=$(< /sys/class/block/nvme0n1p2/start)
  p2_size=$(< /sys/class/block/nvme0n1p2/size)
  printf '%s' "$(((disk_size - p2_start - p2_size) / 2048))"
}

copy_checklists() {
  local destination="$1"
  {
    printf '%s\n' "REDUCTION NIXOS AVEC GPARTED LIVE"
    printf '%s\n' ""
    printf '%s\n' "1. Brancher le secteur. Demarrer GParted Live en mode UEFI depuis Ventoy."
    printf '%s\n' "2. Ouvrir un terminal et executer: btrfs version"
    printf '%s\n' "3. Exiger btrfs-progs v7.0 minimum pour reconnaitre les metadonnees fs-verity."
    printf '%s\n' "4. Si la version est plus ancienne: apt update && apt install --only-upgrade btrfs-progs"
    printf '%s\n' "5. Verifier de nouveau btrfs version. Arreter si elle reste inferieure a v7.0."
    printf '%s\n' "6. Ne pas redemarrer apres la mise a jour, qui existe seulement dans la session Live."
    printf '%s\n' "7. Selectionner uniquement /dev/nvme0n1, environ 953.9 GiB."
    printf '%s\n' "8. Ne jamais modifier /dev/nvme0n1p1, la partition EFI FAT32 de 1 GiB."
    printf '%s\n' "9. Selectionner /dev/nvme0n1p2 puis Partition > Open Encryption."
    printf '%s\n' "10. Entrer la phrase secrete LUKS. Le Btrfs interne doit rester non monte."
    printf '%s\n' "11. Choisir Resize/Move sur p2 ouverte."
    printf '%s\n' "12. Garder Free space preceding et le debut de p2 strictement inchanges."
    printf '%s\n' "13. Saisir 51200 MiB dans Free space following. Ne pas deplacer p2."
    printf '%s\n' "14. La file doit seulement reduire Btrfs, LUKS et la fin de p2."
    printf '%s\n' "15. Appliquer. Ne jamais interrompre l'operation ni son retour arriere."
    printf '%s\n' "16. En cas d'erreur, sauvegarder le rapport et ne pas installer Ubuntu."
    printf '%s\n' "17. Redemarrer NixOS puis relancer ce wizard depuis le depot."
  } > "$destination/GPARTED-CHECKLIST.txt"

  {
    printf '%s\n' "INSTALLATION MANUELLE UBUNTU 26.04"
    printf '%s\n' ""
    printf '%s\n' "1. Demarrer l'ISO Ubuntu en mode UEFI et choisir Try Ubuntu."
    printf '%s\n' "2. Tester affichage, Wi-Fi, webcam, microphone et haut-parleurs."
    printf '%s\n' "3. Lancer Install Ubuntu puis choisir Manual installation."
    printf '%s\n' "4. p1: montage /boot/efi, SANS FORMATAGE."
    printf '%s\n' "5. p2: ne rien modifier. C'est NixOS chiffre."
    printf '%s\n' "6. Espace libre de 50 GiB: creer p3 en ext4, montage /."
    printf '%s\n' "7. Ne pas creer de partition swap separee."
    printf '%s\n' "8. Le recapitulatif doit formater uniquement la nouvelle p3."
    printf '%s\n' "9. Annuler si p1 ou p2 apparait comme devant etre formatee."
    printf '%s\n' "10. Apres installation, tester Ubuntu puis Linux Boot Manager pour NixOS."
    printf '%s\n' "11. Monter Ventoy dans Ubuntu et relancer dual-boot-ubuntu-wizard.sh."
  } > "$destination/UBUNTU-INSTALL-CHECKLIST.txt"
}

banner "Dual-boot NixOS et Ubuntu 26.04"

stage "Preparer NixOS"
if [[ "$(os_id)" != "nixos" ]]; then
  note "Etape NixOS ignoree sur $(os_id)."
else
  if grep -qE 'resumeDevice|resume_offset' "$CONFIGURATION" || grep -q 'swapDevices' "$HARDWARE"; then
    warn "La configuration contient encore des reglages d'hibernation."
    say "Les changements attendus ne sont pas presents. Arret."
    exit 1
  fi

  if grep -q 'resume_offset=' /proc/cmdline; then
    say "La configuration est prete, mais la session actuelle utilise encore l'ancienne generation."
    step "Le wizard va enregistrer la nouvelle generation comme prochain demarrage."
    if confirm "Executer sudo nixos-rebuild boot maintenant ?"; then
      sudo nixos-rebuild boot --flake "$NIXOS_FLAKE" --no-write-lock-file
    else
      warn "Impossible de continuer sans enregistrer la nouvelle generation."
      exit 1
    fi
    say "Redemarrez NixOS, puis relancez ce wizard."
    exit 0
  fi

  if swapon --show=NAME --noheadings 2> /dev/null | grep -qx '/swapfile'; then
    warn "/swapfile est encore actif alors que resume_offset a disparu."
    say "Redemarrez sur la nouvelle generation avant de relancer le wizard."
    exit 1
  fi

  if [[ -e /swapfile ]]; then
    warn "Le fichier /swapfile de 40 Gio va etre supprime. L'hibernation restera desactivee."
    if confirm "Supprimer exactement /swapfile ?"; then
      sudo rm -- /swapfile
    else
      warn "Le redimensionnement reste bloque tant que /swapfile existe."
      exit 1
    fi
  fi

  if [[ ! -e $NIXOS_PREPARED_MARKER ]]; then
    step "Scrub Btrfs complet avant le redimensionnement. Cette operation peut durer."
    sudo btrfs scrub start -Bd /
    sudo btrfs device stats /
    say "NixOS est pret. Le swap actif doit maintenant se limiter au zram."
    swapon --show
    pause "Verifiez qu'aucune erreur non corrigee n'apparait ci-dessus, puis appuyez sur Entree."
    sudo touch "$NIXOS_PREPARED_MARKER"
  else
    note "La preparation et le scrub Btrfs ont deja ete valides."
  fi
fi

stage "Preparer la cle Ventoy"
VENTOY_DIR="${VENTOY_DIR:-$(detect_ventoy_dir || true)}"
UBUNTU_SOURCE=$(find_local_iso "$UBUNTU_ISO" || true)
GPARTED_SOURCE=$(find_local_iso "$GPARTED_ISO" || true)

if [[ -z $UBUNTU_SOURCE ]]; then
  open_url "https://releases.ubuntu.com/26.04/ubuntu-26.04-desktop-amd64.iso"
fi
if [[ -z $GPARTED_SOURCE ]]; then
  open_url "https://downloads.sourceforge.net/gparted/gparted-live-1.8.1-3-amd64.iso"
fi
if [[ -z $UBUNTU_SOURCE || -z $GPARTED_SOURCE ]]; then
  say "Telechargez les ISO manquantes, puis relancez le wizard."
  exit 0
fi

if [[ -z $VENTOY_DIR ]]; then
  ask VENTOY_DIR "Chemin du volume Ventoy monte, par exemple /run/media/tmendy/Ventoy:"
fi

if [[ ! -d $VENTOY_DIR ]]; then
  warn "Le chemin Ventoy n'existe pas: $VENTOY_DIR"
  exit 1
fi

copy_iso_to_ventoy "$UBUNTU_SOURCE" "$VENTOY_DIR" "$UBUNTU_ISO" || {
  warn "La copie de $UBUNTU_ISO vers Ventoy a echoue."
  exit 1
}
copy_iso_to_ventoy "$GPARTED_SOURCE" "$VENTOY_DIR" "$GPARTED_ISO" || {
  warn "La copie de $GPARTED_ISO vers Ventoy a echoue."
  exit 1
}

if [[ ! -f "$VENTOY_DIR/$UBUNTU_ISO" || ! -f "$VENTOY_DIR/$GPARTED_ISO" ]]; then
  warn "Les deux ISO attendues ne sont pas presentes dans $VENTOY_DIR."
  say "$UBUNTU_ISO"
  say "$GPARTED_ISO"
  exit 1
fi

say "Verification SHA-256 de l'ISO Ubuntu sur Ventoy."
printf '%s  %s\n' "$UBUNTU_SHA256" "$VENTOY_DIR/$UBUNTU_ISO" | sha256sum --check --status || {
  warn "La somme SHA-256 de l'ISO Ubuntu est incorrecte."
  exit 1
}
say "ISO Ubuntu valide."
say "Verification SHA-256 de l'ISO GParted sur Ventoy."
printf '%s  %s\n' "$GPARTED_SHA256" "$VENTOY_DIR/$GPARTED_ISO" | sha256sum --check --status || {
  warn "La somme SHA-256 de l'ISO GParted est incorrecte."
  exit 1
}
say "ISO GParted valide."
copy_checklists "$VENTOY_DIR"
if [[ $SCRIPT_DIR != "$VENTOY_DIR" ]]; then
  cp -- "${BASH_SOURCE[0]}" "$VENTOY_DIR/dual-boot-ubuntu-wizard.sh"
  chmod +x "$VENTOY_DIR/dual-boot-ubuntu-wizard.sh"
fi
say "Vidage des ecritures en attente sur la cle Ventoy."
sync "$VENTOY_DIR"
say "Les ISO, leurs sommes et les listes de controle sont pretes sur Ventoy."

stage "Reduire NixOS avec GParted"
if [[ ! -r /sys/class/block/nvme0n1/size || ! -r /sys/class/block/nvme0n1p2/size ]]; then
  warn "Le SSD NVMe attendu n'est pas visible. Arret."
  exit 1
fi

FREE_MIB=$(unallocated_mib_after_p2)
if [[ -b /dev/nvme0n1p3 ]]; then
  note "La partition p3 existe deja. Le redimensionnement est considere termine."
elif ((FREE_MIB >= 51000 && FREE_MIB <= 51400)); then
  say "Espace non alloue detecte apres p2: ${FREE_MIB} MiB."
  say "Le redimensionnement a la taille attendue."
elif ((FREE_MIB < 51000)); then
  warn "Le disque ne contient pas encore les 51200 MiB non alloues."
  step "Ouvrez GPARTED-CHECKLIST.txt sur Ventoy et suivez chaque ligne."
  step "Au redemarrage, choisissez GParted Live en mode UEFI."
  step "Apres l'operation, redemarrez NixOS et relancez ce wizard."
  pause "Prenez une photo de la checklist si necessaire."
  exit 0
else
  warn "L'espace libre apres p2 vaut ${FREE_MIB} MiB, hors de la plage attendue."
  say "Ne lancez pas l'installation Ubuntu avant d'avoir controle la table GPT."
  exit 1
fi

stage "Installer Ubuntu"
if [[ "$(os_id)" == "ubuntu" ]]; then
  ROOT_SOURCE=$(findmnt -no SOURCE /)
  ROOT_FSTYPE=$(findmnt -no FSTYPE /)
  say "Ubuntu demarre depuis $ROOT_SOURCE avec $ROOT_FSTYPE."
  if [[ $ROOT_SOURCE != *"nvme0n1p3"* || $ROOT_FSTYPE != "ext4" ]]; then
    warn "La racine Ubuntu n'utilise pas la p3 ext4 attendue."
    exit 1
  fi
elif [[ -b /dev/nvme0n1p3 ]]; then
  say "NixOS demarre encore apres la creation de la p3."
  touch "$VENTOY_DIR/.dual-boot-nixos-verified"
  step "Redemarrez et choisissez l'entree UEFI Ubuntu."
  step "Montez Ventoy puis relancez dual-boot-ubuntu-wizard.sh depuis la cle."
  exit 0
else
  step "Ouvrez UBUNTU-INSTALL-CHECKLIST.txt sur Ventoy."
  step "Redemarrez sur l'ISO Ubuntu 26.04 en mode UEFI."
  step "Choisissez Try Ubuntu et testez le materiel avant Install Ubuntu."
  warn "Le recapitulatif doit formater uniquement la nouvelle p3."
  pause "Prenez une photo de la checklist si necessaire."
  exit 0
fi

stage "Verifier les deux systemes"
if [[ ! -e "$VENTOY_DIR/.dual-boot-nixos-verified" ]]; then
  say "Ubuntu est installe sur la p3 ext4. Il reste a tester NixOS apres l'installation."
  step "Redemarrez et choisissez Linux Boot Manager dans le menu UEFI."
  step "Sous NixOS, montez Ventoy et relancez ce wizard depuis le depot."
  step "Le wizard enregistrera le test, puis vous demandera de revenir dans Ubuntu."
  exit 0
fi
say "Ubuntu et NixOS ont tous les deux demarre depuis la nouvelle table GPT."
if command -v efibootmgr > /dev/null 2>&1; then
  efibootmgr | sed -n '1,30p'
fi

stage "Valider PSI"
if [[ "$(os_id)" != "ubuntu" ]]; then
  warn "Cette etape doit etre executee depuis Ubuntu."
  exit 1
fi
say "PSI prend officiellement en charge Ubuntu 26.04."
step "Deconnectez tout ecran supplementaire et gardez une seule camera et un seul microphone."
step "Coupez les VPN. Utilisez les haut-parleurs, jamais un casque ou des ecouteurs."
step "Dans Parametres > Son, testez l'entree micro et les haut-parleurs."
step "Testez la webcam avec Cheese ou dans le diagnostic video."
if command -v xrandr > /dev/null 2>&1; then
  xrandr --listmonitors || true
fi
if command -v nmcli > /dev/null 2>&1; then
  nmcli connection show --active || true
fi
open_url "https://video-diagnostics.twilio.com/"
open_url "https://test-takers.psiexams.com/linux/test-pro"
step "Executez le System Check et le Tutorial Test aujourd'hui."
step "Le 25 aout, redemarrez Ubuntu et commencez le check-in a 13 h 30."
step "Lancez PSI Secure Browser depuis le bureau avec Run as a program, pas depuis le terminal."
pause "Appuyez sur Entree uniquement lorsque le diagnostic et le tutoriel sont valides."

finish
